name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-github:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and install github-cicd
      run: |
        cd github/github-cicd-actions
        mvn clean install

    - name: Build Docker image for github-cicd
      run: |
        cd github/github-cicd-actions
        docker build -t ${{ secrets.DOCKER_USERNAME }}/github:github -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/github:github

  #gitlab-cicd project
  build-gitlab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and install gitlab-cicd
      run: |
        cd gitlab/gitlab-cicd-actions
        mvn clean install

    - name: Build Docker image for gitlab-cicd
      run: |
        cd gitlab/gitlab-cicd-actions
        docker build -t ${{ secrets.DOCKER_USERNAME }}/gitlab:gitlab -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/gitlab:gitlab

  #jenkins-cicd project
  build-jenkins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and install jenkins-cicd
      run: |
        cd jenkins/jenkins-cicd-actions
        mvn clean install

    - name: Build Docker image for jenkins-cicd
      run: |
        cd jenkins/jenkins-cicd-actions
        docker build -t ${{ secrets.DOCKER_USERNAME }}/jenkins:jenkins -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/jenkins:jenkins
