name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and install github-cicd
      run: |
        cd github/github-cicd-actions
        mvn clean install
        # Upload artifacts
        mkdir -p $GITHUB_WORKSPACE/artifacts/github
        cp target/github.jar $GITHUB_WORKSPACE/artifacts/github
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: github
        path: $GITHUB_WORKSPACE/artifacts/github


    - name: Build and install gitlab-cicd
      run: |
        cd gitlab/gitlab-cicd-actions
        mvn clean install
        # Upload artifacts
        mkdir -p $GITHUB_WORKSPACE/artifacts/gitlab
        cp target/gitlab.jar $GITHUB_WORKSPACE/artifacts/gitlab
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gitlab
        path: $GITHUB_WORKSPACE/artifacts/gitlab

    - name: Build and install jenkins-cicd
      run: |
        cd jenkins/jenkins-cicd-actions
        mvn clean install
        # Upload artifacts
        mkdir -p $GITHUB_WORKSPACE/artifacts/jenkins
        cp target/jenkins.jar $GITHUB_WORKSPACE/artifacts/jenkins
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jenkins
        path: $GITHUB_WORKSPACE/artifacts/jenkins

  push:
     needs: build
     runs-on: ubuntu-latest

     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Download and Build Docker Image for github-cicd
         run: |
           IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/github"
           TAG="github"
           cd github/github-cicd-actions
           # Download artifacts
           mkdir -p target
           cp $GITHUB_WORKSPACE/artifacts/github/github.jar target
           docker build -t $IMAGE_NAME:$TAG -f Dockerfile .
           docker push $IMAGE_NAME:$TAG

       - name: Download and Build Docker Image for gitlab-cicd
         run: |
           IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/gitlab"
           TAG="latest"
           cd gitlab/gitlab-cicd-actions
           # Download artifacts
           mkdir -p target
           cp $GITHUB_WORKSPACE/artifacts/gitlab/gitlab.jar target
           docker build -t $IMAGE_NAME:$TAG -f Dockerfile .
           docker push $IMAGE_NAME:$TAG

       - name: Download and Build Docker Image for jenkins-cicd
         run: |
           IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/jenkins"
           TAG="latest"
           cd jenkins/jenkins-cicd-actions
           # Download artifacts
           mkdir -p target
           cp $GITHUB_WORKSPACE/artifacts/jenkins/jenkins.jar target
           docker build -t $IMAGE_NAME:$TAG -f Dockerfile .
           docker push $IMAGE_NAME:$TAG
