name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-github:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and install github-cicd
      run: |
        cd github/github-cicd-actions
        mvn clean install

    - name: Tagging 
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/github"
        GITHUB_TAGG="$IMAGE_NAME:GITHUB"
        echo "Tag Is: $GITHUB_TAGG"
        echo "GITHUB_TAGG=$GITHUB_TAGG" >> $GITHUB_ENV

    - name: Build Docker image for github-cicd
      run: |
        cd github/github-cicd-actions
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t ${{ env.GITHUB_TAGG }} .
        docker push ${{ env.GITHUB_TAGG }}

  #gitlab-cicd project
  build-gitlab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and install gitlab-cicd
      run: |
        cd gitlab/gitlab-cicd-actions
        mvn clean install

    - name: Tagging 
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/gitlab"
        GITLAB_TAGG="$IMAGE_NAME:GITHUB"
        echo "Tag Is: $GITLAB_TAGG"
        echo "GITLAB_TAGG=$GITLAB_TAGG" >> $GITHUB_ENV

    - name: Build Docker image for gitlab-cicd
      run: |
        cd gitlab/gitlab-cicd-actions
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t ${{ env.GITLAB_TAGG }} .
        docker push ${{ env.GITLAB_TAGG }}

  #jenkins-cicd project
  build-jenkins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and install jenkins-cicd
      run: |
        cd jenkins/jenkins-cicd-actions
        mvn clean install

    - name: Tagging 
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/jenkins"
        GITLAB_TAGG="$IMAGE_NAME:JENKINS"
        echo "Tag Is: $JENKINS_TAGG"
        echo "JENKINS_TAGG=$JENKINS_TAGG" >> $GITHUB_ENV

    - name: Build Docker image for jenkins-cicd
      run: |
        cd jenkins/jenkins-cicd-actions
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t ${{ env.JENKINS_TAGG }} .
        docker push ${{ env.JENKINS_TAGG }}
